### ISSUE TITLE
Roadmap: Wing 0.3.0 development tasks

### ISSUE THREAD

**Issue by NCBM** [nonedesktop/nonebot-desktop-wing#1]
* [x] Update resources URL
* [x] Upgrade code to Python 3.10
* [ ] Redesign code interfaces
  * [x] Refactor inconsistent parameters
  * [ ] Improve code
